# Generated by Django 6.0.2 on 2026-02-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
