# Generated by Django 6.0.2 on 2026-02-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_users_options_remove_users_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
